change tabs to spaces

diff --git a/scripts/.local/bin/setbg b/scripts/.local/bin/setbg
--- a/scripts/.local/bin/setbg
+++ b/scripts/.local/bin/setbg
@@ -8,12 +8,12 @@
 file_type="$(file --mime-type -b "$1")"
 
 case "$file_type" in
-	"image/png")
-		cp "$1" "$XDG_DATA_HOME/wallies/current_wallie.png"
-		xwallpaper --output eDP1 --center "$XDG_DATA_HOME/wallies/current_wallie.png"
-		notify-send "Wallpaper set!"
-		;;
-	*)
-		echo "Invalid file type. Not compatible!" && exit 1
-		;;
+  "image/png")
+    cp "$1" "$XDG_DATA_HOME/wallies/current_wallie.png"
+    xwallpaper --output eDP1 --center "$XDG_DATA_HOME/wallies/current_wallie.png"
+    notify-send "Wallpaper set!"
+    ;;
+  *)
+    echo "Invalid file type. Not compatible!" && exit 1
+    ;;
 esac
