add support for jpg - setbg

diff --git a/scripts/.local/bin/setbg b/scripts/.local/bin/setbg
--- a/scripts/.local/bin/setbg
+++ b/scripts/.local/bin/setbg
@@ -3,17 +3,22 @@
 # author: The_philosopher
 # description: sets a background
 
-[ -z "$1" ] && echo "setbg needs an argument of PNG type!" && exit 1
+[ -z "$1" ] && echo "setbg needs an argument of image type!" && exit 1
 
 file_type="$(file --mime-type -b "$1")"
 
 case "$file_type" in
-  "image/png")
-    cp "$1" "$XDG_DATA_HOME/wallies/current_wallie.png"
-    xwallpaper --output eDP1 --center "$XDG_DATA_HOME/wallies/current_wallie.png"
-    notify-send "Wallpaper set!"
-    ;;
-  *)
-    echo "Invalid file type. Not compatible!" && exit 1
-    ;;
+    "image/png")
+        cp "$1" "$XDG_DATA_HOME/wallies/current_wallie.png"
+        xwallpaper --output eDP1 --maximize "$XDG_DATA_HOME/wallies/current_wallie.png"
+        notify-send "Wallpaper set!"
+        ;;
+    "image/jpeg")
+        cp "$1" "$XDG_DATA_HOME/wallies/current_wallie.jpg"
+        xwallpaper --output eDP1 --maximize "$XDG_DATA_HOME/wallies/current_wallie.jpg"
+        notify-send "Wallpaper set!"
+        ;;
+    *)
+        echo "Invalid file type. Not compatible!" && exit 1
+        ;;
 esac
